name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # no need to document the AppImage style arch names here, we can use gea to fix the binary's filename before upload
        DOCKER_ARCH_PREFIX:
          - ""
          - "i386/"
          - "arm32v7/"
          - "arm64v8/"
      fail-fast: false

    name: ${{ format('{0}{1}', matrix.DOCKER_ARCH_PREFIX, 'alpine:latest') }}

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build in Docker
        run: bash ci/build-in-docker.sh
        env:
          DOCKER_ARCH_PREFIX: ${{ matrix.DOCKER_ARCH_PREFIX }}

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        if: matrix.BUILD_TYPE != 'coverage'
        with:
          name: gea ${{ matrix.DOCKER_ARCH_PREFIX }}
          path: gea-*

  upload:
    name: Create release and upload artifacts
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Inspect directory after downloading artifacts
        run: ls -alFR
      - name: Create release and upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
            chmod +x pyuploadtool-x86_64.AppImage
            ./pyuploadtool-x86_64.AppImage **/gea-*
